"""Generate one Claude Code subagent per ladder rung from a base agent file.

Each cell is `<agents-dir>/<name>-<rung>-medium.md`: the body of the base file verbatim,
with name, description, model and effort pinned. Regenerate rather than hand-edit. The
rungs and model ids come from the ratchet config, so the ladder has one owner.

    python gen_agents.py --agents-dir ~/.claude/agents            # write the cells
    python gen_agents.py --agents-dir ~/.claude/agents --check    # exit 1 if any is stale
    python gen_agents.py --base my-worker.md --name my-worker --effort medium \
        --config ../ratchet.toml --agents-dir .claude/agents

Defaults: `--base worker.md` beside this file, `--name` from the base file's frontmatter
`name`, `--effort medium`, and the config found by the usual ratchet lookup.
Stdlib only.
"""

from __future__ import annotations

import argparse
import importlib.util
import pathlib
import re
import sys

HERE = pathlib.Path(__file__).resolve().parent
TOOL = HERE.parent / "tools" / "ratchet.py"
FRONT = re.compile(r"---\n(.*?)\n---\n(.*)", re.S)
NOTE = "<!-- generated by gen_agents.py from {base}; do not edit -->\n"


def load_tool(path: pathlib.Path):
    spec = importlib.util.spec_from_file_location("ratchet", path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def split_front(base: str) -> "tuple[str, str]":
    m = FRONT.match(base)
    if not m:
        sys.exit("the base agent file needs YAML frontmatter delimited by ---")
    return m.group(1), m.group(2)


def render(base: str, name: str, rung: str, model: str, effort: str, base_name: str) -> str:
    front, body = split_front(base)
    front = re.sub(r"^name: .*$", "name: %s-%s-%s" % (name, rung, effort), front, flags=re.M)
    front = re.sub(r"^description: .*$",
                   "description: Ladder rung cell (%s, effort %s) — one task unit under "
                   "ratchet task records. Dispatch by name for that rung of a task."
                   % (model, effort), front, flags=re.M)
    front = re.sub(r"^model: .*$", "model: %s" % model, front, flags=re.M)
    if re.search(r"^effort: ", front, flags=re.M):
        front = re.sub(r"^effort: .*$", "effort: %s" % effort, front, flags=re.M)
    else:
        front += "\neffort: %s" % effort
    return "---\n%s\n---\n%s%s" % (front, NOTE.format(base=base_name), body)


def main(argv: "list[str]") -> int:
    ap = argparse.ArgumentParser(prog="gen_agents.py",
                                 description=(__doc__ or "").split("\n\n")[0])
    ap.add_argument("--base", default=str(HERE / "worker.md"), help="base agent markdown file")
    ap.add_argument("--name", help="cell name prefix; default the base file's frontmatter name")
    ap.add_argument("--agents-dir", required=True, help="where the cells are written")
    ap.add_argument("--effort", default="medium", help="effort pinned in every cell")
    ap.add_argument("--config", help="an ratchet ratchet.toml/ratchet.json")
    ap.add_argument("--tool", default=str(TOOL), help="path to ratchet.py")
    ap.add_argument("--check", action="store_true", help="exit 1 if any cell is missing or stale")
    a = ap.parse_args(argv)

    base_path = pathlib.Path(a.base).expanduser()
    base = base_path.read_text(encoding="utf-8").replace("\r\n", "\n")
    front, _ = split_front(base)
    name = a.name
    if not name:
        m = re.search(r"^name: (.+)$", front, flags=re.M)
        name = m.group(1).strip() if m else base_path.stem
    mod = load_tool(pathlib.Path(a.tool).expanduser())
    cfg = mod.load_config(a.config)

    agents = pathlib.Path(a.agents_dir).expanduser()
    stale = []
    if not a.check:
        agents.mkdir(parents=True, exist_ok=True)
    for rung, model in cfg.ladder.items():
        path = agents / ("%s-%s-%s.md" % (name, rung, a.effort))
        text = render(base, name, rung, model, a.effort, base_path.name)
        if a.check:
            if not path.exists() or path.read_text(encoding="utf-8").replace("\r\n", "\n") != text:
                stale.append(path.name)
        else:
            path.write_text(text, encoding="utf-8", newline="\n")
            print(path.name)
    if stale:
        print("stale:", ", ".join(stale))
        return 1
    if a.check:
        print("%d cells up to date (config: %s)" % (len(cfg.ladder), cfg.path or "defaults"))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
